### ISSUE TITLE
Problem with Preview inside Delphi 10.4.1 Sydney

### ISSUE THREAD

**Issue by acambule** [EtheaDev/SVGShellExtensions#2]
Hello,

I'm not shure if it was meant to work, but i installed this Extension in the hope to see svg preview inside of delphi dialog (in designtime).

And partly it works. When i open the imagelist to add a new svg is can see the preview like this:
![grafik](https://user-images.githubusercontent.com/22659382/108473567-7c398900-728e-11eb-8fa4-68abfc32b53a.png)

changing from one svg to an other it looks like this:
![grafik](https://user-images.githubusercontent.com/22659382/108473960-fd911b80-728e-11eb-8ea8-5f10f0ad8a01.png)

The preview does not update appropriate.

Edit: Changing the size of the preview panel, forces the preview to update and that corrects the preview.

Saluti da Berlino
Antonio Cambule

**Comment by carloBarazzetta** [comment]
Yes, I know this bug, it happens when you have more than one screen and you open Windows Explorer on the secondary screen or drag it to it. For now I have not found a solution but I have seen that other previews (eg Adobe's one for PDFs) have the same type of problem.
From some tests I've done it seems that Explorer notifies the preview with the wrong size.
I leave this issue open because sooner or later I have to try to solve it.
ciao Antonio
![image](https://user-images.githubusercontent.com/7803548/108478021-45667180-7294-11eb-97d4-558ed3e206b4.png)

**Comment by birbilis** [comment]
Probably should use windows 10 feedback center to let MS know in case it's their bug

**Comment by AngusJohnson** [comment]
I've also encountered  a preview sizing problem (but using the pre-compiled extension in Windows 10). The previiew window will on occasions maximize to the full screen with no way to shrink it except to close the window and disable previewing. This happens frequently enough to be very annoying, but otherwise the extension works really well.

**Comment by carloBarazzetta** [comment]
Hi Angus, I have the same problem sometimes, especially when I work with multiple monitors ... My Shell extension is based on Rodrigo Ruz's great project here: https://github.com/RRUZ/delphi-preview-handler and sometimes the problem also occurs with the preview of Rodrigo ...
I will try to check if Rodrigo has fixed this problem in the meantime.
